language: node_js
node_js:
  - "10"
cache: 
  directories: 
    - node_modules
env:
  matrix:
  - REACT=16.4
  - REACT=16.5
  - REACT=16.6
sudo: false
script:
  - npm test
after_success:
  - npm run coverage
deploy: 
  provider: pages 
  skip_cleanup: true 
  github_token: $github_token 
  local_dir: build 
  on: 
    branch: master
